apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: server
          image: frontend
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          - name: RESTAURANT_SERVICE_ADDR
            value: "restaurantservice:50051"
          - name: USER_SERVICE_ADDR
            value: "userservice:3550"
          - name: CART_SERVICE_ADDR
            value: "cartservice:7070"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "recommendationservice:7000"
          - name: MAIL_SERVICE_ADDR
            value: "mailservice:9555"
          - name: CHECKOUT_SERVICE_ADDR
            value: "checkoutservice:5050"
          - name: ENV_PLATFORM
            value: "gcp"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: LoadBalancer
  loadBalancerIP: 104.198.68.112
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
