apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailservice
spec:
  selector:
    matchLabels:
      app: mailservice
  template:
    metadata:
      labels:
        app: mailservice
    spec:
      containers:
      - name: server
        image: mailservice
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
        - name: USER_SERVICE_ADDR
          value: "userservice"
        - name: USER_SERVICE_PORT
          value: "3550"
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mailservice
spec:
  type: ClusterIP
  selector:
    app: mailservice
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555
