apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
spec:
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
      - name: server
        image: recommendationservice
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        - name: USER_SERVICE_ADDR
          value: "userservice"
        resources:
          requests:
            cpu: 300m
            memory: 180Mi
          limits:
            cpu: 400m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
spec:
  type: ClusterIP
  selector:
    app: recommendationservice
  ports:
  - name: grpc
    port: 7000
    targetPort: 7000
