apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantservice
spec:
  selector:
    matchLabels:
      app: restaurantservice
  template:
    metadata:
      labels:
        app: restaurantservice
    spec:
      containers:
      - name: server
        image: restaurantservice
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: MONGO_ADDR
          value: " mongo-mongodb.default.svc.cluster.local"  
        - name: MONGO_PORT
          value: "27017" 
        - name: MONGODB_ROOT_PASSWORD
          value: "admin"
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: restaurantservice
spec:
  type: ClusterIP
  selector:
    app: restaurantservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
